# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*OPUS/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = CC-BY-NC-SA
COPYRIGHT = 

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=<p>JW300 is a parallel corpus of over 300 languages with around 100 thousand parallel sentences per language pair on average. The corpus has been compiled by Zeljko Agic and Ivan Vulic.</p>
EXTRAHTML=<h3>License</h3><p>For all practical purpose, the license is CC-BY-NC-SA.</p><p>Still, <a href="https://www.jw.org/en/terms-of-use/">jw.org maintains custom terms of use</a>; in doubt, make sure to observe their license!</p>

CITENOTE=<p>Please, cite the following paper: <a href="https://www.aclweb.org/anthology/papers/P/P19/P19-1310/">Željko Agić, Ivan Vulić: <i>"JW300: A Wide-Coverage Parallel Corpus for Low-Resource Languages"</i></a>, In Proceedings of the 57th Annual Meeting of the Association for Computational Linguistics (ACL), 2019. Acknowledge also OPUS by <a href="http://opus.lingfil.uu.se/LREC2012.txt">citing the following article</a>:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)<br/></p>
