# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = OpenSubtitles2018
VERSION = 


# CITENOTE sets the text to be used for citing the corpus
# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

CITENOTE=Please cite the following article if you use any part of the corpus in your own work:<br/> P. Lison and J. Tiedemann, 2016, <a href="http://stp.lingfil.uu.se/~joerg/paper/opensubs2016.pdf"><i>OpenSubtitles2016: Extracting Large Parallel Corpora from Movie and TV Subtitles.</i></a> In Proceedings of the 10th International Conference on Language Resources and Evaluation (LREC 2016)<br/>

SRCHTML=<p>This is a new collection of translated movie subtitles from <a href="http://www.opensubtitles.org/">http://www.opensubtitles.org/</a>.<br/><a href="http://www.opensubtitles.org/"><img src="https://static.opensubtitles.org/gfx/logo.gif"></a></p><p><b>IMPORTANT:</b> If you use the OpenSubtitle corpus: Please, add a link to <b>http://www.opensubtitles.org/</b> to your website and to your reports and publications produced with the data! I promised this when I got the data from the providers of that website!</p> <p> This is a slightly cleaner version of the subtitle collection using improved sentence alignment and better language checking.</p>

EXTRAHTML=<p>We also provide <b>sentence alignments between alternative subtitle uploads</b>. This produces a lot of repeated material and, therefore, we do not provide data sets that are compiled into plain text or TMX format. Instead, you can download the standoff annotation of the sentence alignment from the <a href="/index.php">form at the top-level website</a>. There are links to [alt] in the "other files" column of the search result if they exist.</p><p>${CORPUS} also includes <b>intra-lingual sentence alignments</b> between alternative subtitle uploads in the same language. To access those files, search for resources with the same source and target language using the form on the <a href="/index.php">top-level website</a>. The intra-lingual links are divided into different categories (listed in the column "other files" in the search result):</p>\
<ul>\
<li><b>insert:</b> Sentence pairs that differ only by some inserted text on one side</li>\
<li><b>other:</b> Other types of sentence pairs; probably paraphrases and/or stylistically different subtitles.</li>\
<li><b>pct:</b> Sentence pairs that differ only in punctuation characters.</li>\
<li><b>spell:</b> Sentence pairs that differ in a few characters only that looks suspiciously like misspellings.</li>\
</ul>\
<p>For more information, please look at <br/> J. Tiedemann, 2016, <a href="http://stp.lingfil.uu.se/~joerg/paper/lrec2016.pdf"><i>Finding Alternative Translations in a Large Corpus of Movie Subtitles.</i></a><br/> In Proceedings of the 10th International Conference on Language Resources and Evaluation (LREC 2016)<br/>(and, please, cite the paper as well).</p>


## directory on abel with the converted subtitle files.

ABEL         = abel.uio.no
ABEL_USER    = joerg
ABEL_TARDIR  = /projects/researchers/researchers01/plison/data/opensubs2018
ABEL_WORKDIR = /work/users/joerg/OPUS/corpus/OpenSubtitles2018
