# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = SETIMES
VERSION = v1


# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=<p>A parallel corpus of news articles in the Balkan languages, originally extracted from <a href="http://www.setimes.com">http://www.setimes.com</a>. The corpus is PUBLIC DOMAIN, but if you use it in your work, please cite: Francis M. Tyers and Murat Alperen (2010), "South-East European Times: A parallel corpus of the Balkan languages".</p>
EXTRAHTML=
