# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = openUnder-PSI
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/greek-english-parallel-corpus-from-eqf-referencing-report-processed/20bec5fc507311e9a7e100155d026706eb905dc6c4954e1bbd6df2dba5ae62f8/">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=Greek-English parallel corpus from EQF Referencing Report (Processed)   
EXTRAHTML=ELRC-1981-EQF_Referencing_Report is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/greek-english-parallel-corpus-from-eqf-referencing-report-processed/20bec5fc507311e9a7e100155d026706eb905dc6c4954e1bbd6df2dba5ae62f8/">https://www.elrc-share.eu</a>
# CITENOTE=
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/greek-english-parallel-corpus-from-eqf-referencing-report-processed/20bec5fc507311e9a7e100155d026706eb905dc6c4954e1bbd6df2dba5ae62f8/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
