# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = openUnder-PSI
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/bilingual-hr-en-parallel-corpus-from-the-national-and-university-library-in-zagreb-website-processed/7dc064e6fe0111e8b7d400155d02670638c10a71c8ce41fda665a16beaa57d52/">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=Bilingual hr-en parallel corpus from the National and University Library in Zagreb  website (Processed)   
EXTRAHTML=ELRC-1058-University_Library_Zagreb is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/bilingual-hr-en-parallel-corpus-from-the-national-and-university-library-in-zagreb-website-processed/7dc064e6fe0111e8b7d400155d02670638c10a71c8ce41fda665a16beaa57d52/">https://www.elrc-share.eu</a>
# CITENOTE=
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/bilingual-hr-en-parallel-corpus-from-the-national-and-university-library-in-zagreb-website-processed/7dc064e6fe0111e8b7d400155d02670638c10a71c8ce41fda665a16beaa57d52/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
