# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v2022

RELEASE_DATE = 05/18/2022

LICENSE = CC-BY-SA
COPYRIGHT = 

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML = This corpus has been collected within the framework of “Estonian Open Parallel Corpus”. The purpose of the project is to create a significant amount of language resources to improve machine translation systems.
# EXTRAHTML=Simple example corpus
# CITENOTE=

CONTACT = Roberts Rozis <roberts.rozis@tilde.com>
SOURCE_URL = https://metashare.tilde.com/repository/browse/eopc-2022-estonian-open-parallel-corpus-2022-estonian-russian/dcb9f35cd69511eca6e4fa163e9d454714176e41bcd048e3a1cf266a6fb68a3f/
