# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = RF
VERSION = v1


# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=<p>Declarations of Government Policy by the Swedish Government</p>

EXTRAHTML=<p>RF is a tiny parallel corpus of the Declarations of the Swedish Government and its translations. The corpus was originally compiled by Erik Tjong Kim Sang (At Uppsala University at that time) and mainly serves as a small example corpus and for educational purposes.</p>
