# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = RF
VERSION = 0.1


# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=<p>Declarations of Government Policy by the Swedish Government</p>
EXTRAHTML=<p>Simple example corpus</p>
