# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = publicDomainpublicDomain
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/trilingual-documents-related-to-international-judicial-cooperation-in-civil-matters-greek-english-french-processed/b904a53601e411e8b7d400155d026706d6e1015a5460467ca72d0dfa71e5823e/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Trilingual Documents related to International Judicial Cooperation in Civil Matters (Greek-English-French) (Processed)   
EXTRAHTML=ELRC-646-International_Judicial_Cooperation_Civil_Matters is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/trilingual-documents-related-to-international-judicial-cooperation-in-civil-matters-greek-english-french-processed/b904a53601e411e8b7d400155d026706d6e1015a5460467ca72d0dfa71e5823e/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/trilingual-documents-related-to-international-judicial-cooperation-in-civil-matters-greek-english-french-processed/b904a53601e411e8b7d400155d026706d6e1015a5460467ca72d0dfa71e5823e/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
