# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = mytest
VERSION = 0.1


# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=This is my first parallel corpus
EXTRAHTML=Simple example corpus
