# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = openUnder-PSI
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/spanish-portuguese-website-parallel-corpus-processed/a548e4a6312911e9a4d400155d0267063d30a93b94b34ceebe168ca3af831e1b/">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=Spanish-Portuguese website parallel corpus (Processed)   
EXTRAHTML=ELRC-1254-government_websites_Spanish_Portuguese is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/spanish-portuguese-website-parallel-corpus-processed/a548e4a6312911e9a4d400155d0267063d30a93b94b34ceebe168ca3af831e1b/">https://www.elrc-share.eu</a>
# CITENOTE=
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/spanish-portuguese-website-parallel-corpus-processed/a548e4a6312911e9a4d400155d0267063d30a93b94b34ceebe168ca3af831e1b/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
