<table><tr>
<td><a href="index.php">Home</a>&nbsp;/&nbsp;<a href="/bin/opuscqp.pl">Query</a>&nbsp;/&nbsp;<a href="/lex.php">WordAlign</a>&nbsp;/&nbsp;<a href="/trac">Wiki</a>&nbsp;&nbsp;&nbsp;</td>
<td>
      [<a href="ada83.php">ada83</a>] 
      [<a href="bible-uedin.php">bible</a>] 
      [<a href="Bianet.php">bianet</a>] 
      [<a href="Books.php">books</a>] 
      [<a href="CAPES.php">CAPES</a>] 
      [<a href="DGT.php">DGT</a>]
      [<a href="DOGC.php">DOGC</a>]
      [<a href="ECB.php">ECB</a>] 
      [<a href="EhuHac.php">EhuHac</a>]
      [<a href="EiTB-ParCC.php">EiTB</a>]
      [<a href="Elhuyar.php">Elhuyar</a>]
      [<a href="ELRC.php">ELRC</a>]
      [<a href="EMEA.php">EMEA</a>]
      [<a href="EUbookshop.php">EUbooks</a>] 
      [<a href="EUconst.php">EU</a>]
<!--  [<a href="Europarl-v3.php">Europarl3</a>] -->
      [<a href="Europarl.php">Europarl</a>]
      [<a href="Finlex.php">finlex</a>]
      [<a href="fiskmo.php">fiskmö</a>]
      [<a href="giga-fren.php">giga</a>]
      [<a href="GNOME.php">GNOME</a>]
      [<a href="GlobalVoices.php">GlobalVoices</a>]
      [<a href="hrenWaC.php">hren</a>]
      [<a href="infopankki-v1.php">infopankki</a>]
      [<a href="JRC-Acquis.php">JRC</a>]
      [<a href="JW300.php">JW300</a>]
      [<a href="KDE4.php">KDE4</a>/<a href="KDEdoc.php">doc</a>] 
      [<a href="MBS.php">MBS</a>]
      [<a href="memat.php">memat</a>]
      [<a href="MontenegrinSubs.php">MontenegrinSubs</a>]
      [<a href="MultiUN.php">MultiUN</a>] 
      [<a href="MultiParaCrawl.php">MultiParaCrawl</a>]
      [<a href="News-Commentary-v9.1.php">NCv9</a>/<a href="News-Commentary-v11.php">v11</a>/<a href="News-Commentary-v14.php">v14</a>]
      [<a href="OfisPublik.php">Ofis</a>]
      [<a href="OpenOffice-v2.php">OO</a>/<a href="OpenOffice-v3.php">OO3</a>] 
      [<a href="OpenSubtitles-v1.php">subs<a>/<a href="OpenSubtitles-v2016.php">16</a>/<a href="OpenSubtitles-v2018.php">18</a>]
<!--  [<a href="OpenSubtitles-v1.php">subs<a>/<a href="OpenSubtitles-v2012.php">12</a>/<a href="OpenSubtitles-v2013.php">13</a>/<a href="OpenSubtitles-v2016.php">16</a>/<a href="OpenSubtitles-v2018.php">18</a>] -->
      [<a href="opus-100.php">Opus100</a>]
      [<a href="ParaCrawl.php">ParaCrawl</a>]
      [<a href="ParCor">ParCor</a>]
      [<a href="PHP.php">PHP</a>]
      [<a href="QED.php">QED</a>]
      [<a href="sardware.php">sardware</a>]
      [<a href="SciELO.php">SciELO</a>]  
      [<a href="SETIMES.php">SETIMES</a>] 
      [<a href="SPC.php">SPC</a>]
      [<a href="Tatoeba.php">Tatoeba</a>] 
      [<a href="Tanzil.php">Tanzil</a>]
      [<a href="TEP.php">TEP</a>]
      [<a href="TedTalks.php">TedTalks</a>]
      [<a href="TED2013.php">TED</a>]
      [<a href="TildeMODEL.php">Tilde</a>]
      [<a href="Ubuntu.php">Ubuntu</a>]
      [<a href="UN.php">UN</a>]
      [<a href="UNPC.php">UNPC</a>]
      [<a href="wikimedia.php">Wikimedia</a>]
      [<a href="Wikipedia.php">Wikipedia</a>]
      [<a href="WikiSource.php">WikiSource</a>]
      [<a href="WMT-News.php">WMT</a>]
      [<a href="XhosaNavy.php">XhosaNavy</a>]
</td></tr></table>
<br/>
