# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = OpenOffice
VERSION = v3


# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=<p>A collection of documents from <a href="http://www.openoffice.org/">http://www.openoffice.org/</a>.</p>
EXTRAHTML=
