# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = MPC1
VERSION = v1


# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=
EXTRAHTML=
