# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = CC-BY-NC-4.0
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/da-en-danish-ministry-of-higher-education-and-science-3-processed/34999b5c6d1b11e7b7d400155d026706d8c5c7566d9844ecb8cab52e08e275cf/">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=DA-EN Danish Ministry of Higher Education and Science 3 (Processed)   
EXTRAHTML=ELRC-394-Danish_Higher_Education_Science_3 is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/da-en-danish-ministry-of-higher-education-and-science-3-processed/34999b5c6d1b11e7b7d400155d026706d8c5c7566d9844ecb8cab52e08e275cf/">https://www.elrc-share.eu</a>
# CITENOTE=
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/da-en-danish-ministry-of-higher-education-and-science-3-processed/34999b5c6d1b11e7b7d400155d026706d8c5c7566d9844ecb8cab52e08e275cf/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
