# -*-makefile-*-
include ../Makefile.def


all: align-all


include ../../Makefile.def
include ../../Makefile.align


## srtalign does not seem to work well ....
## (possibly try to re-align with dic later?)


# ## define srtalign as the alignment tool
# ## (requires different kind of command line flags)

# SENTALIGN=srtalign -b -i 5 -m 10 -c 0.5
# ALGSIDOPT=-S
# ALGTIDOPT=-T
# ALGSRCOPT=
# ALGTRGOPT=
# ALGOUTOPT= | gzip -c > 
