# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*OPUS/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = <a href="https://github.com/omidkashefi/Mizan/blob/master/LICENSE.md">CC-BY-4.0</a>
COPYRIGHT = 

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=MIZAN: A Large Persian-English Parallel Corpus available from <a href="https://github.com/omidkashefi/Mizan/">https://github.com/omidkashefi/Mizan/</a>
EXTRAHTML=
CITENOTE=Please cite Kashefi, O. (2018). <a href="https://arxiv.org/abs/1801.02107v2">MIZAN: a large persian-english parallel corpus. Computing Research Repository</a>, arXiv:1801.02107. [<a href="https://dblp.uni-trier.de/rec/bibtex0/journals/corr/abs-1801-02107">bibtex</a>] and also acknowledge OPUS for providing this service
