# -*-makefile-*-
#

all:
	${MAKE} all-wordalign

include ../Makefile.def
include ../../Makefile.def
include ../../Makefile.wordalign

CORPUSXML        = ${CORPUSHOME}/parsed
CORPUSWORDALIGN  = ${OPUSWORDALIGN}/${CORPUS}/ud


