# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = Tatoeba
# VERSION = v20190709
VERSION = v$(shell date +%F)


LICENSE = <a href="https://creativecommons.org/licenses/by/2.0/fr/">CC BY 2.0 FR</a>
COPYRIGHT = see <a href="https://tatoeba.org/eng/terms_of_use">https://tatoeba.org/eng/terms_of_use</a>


# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=This is a collection of translated sentences from <a href="http://tatoeba.org/">Tatoeba</a>
EXTRAHTML=<p>License: <a href="https://creativecommons.org/licenses/by/2.0/fr/">CC–BY 2.0 FR</a></p>
