# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = Tatoeba
VERSION = v2
# VERSION = $(shell date +%F)


# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=This is a collection of translated sentences from <a href="http://tatoeba.org/">Tatoeba</a>
EXTRAHTML=
