# -*-makefile-*-
#
# name & version of the corpus



## - specify the server of the OPUS repository
## - specify the repository name and the user name
## (this assumes that ssh keys are set up to access the server)

# OPUSRR_HOST = vm0081.kaj.pouta.csc.fi
OPUSRR_HOST   = vm1637.kaj.pouta.csc.fi
OPUSRR_USER   = cloud-user
REPO_NAME     = infopankki
REPO_USER     = joerg



## CORPUSNAME = subdir under /corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
## TODO: can we take that from the OPUSRR repo?
VERSION = v1


LICENSE = CC–BY 4.0 
COPYRIGHT = 

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Source: <a href+"http://www.infopankki.fi">http://www.infopankki.fi</a> via the <a href="https://github.com/City-of-Helsinki/infopankki-api">Open Data API</a>
EXTRAHTML=The corpus was compiled as part of the <a href="https://blogs.helsinki.fi/fiskmo-project/">fiskmö project</a>
