# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = WikiSource
VERSION = v1


# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=<a href="http://wikisource.org">http://wikisource.org</a>
EXTRAHTML=
