# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = CC-BY-SA-3.0
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/estonian-english-parallel-corpus-from-the-estonian-classification-of-economic-activities-emtak/8f70180ab83f11e9a7e100155d0267060b99d0ceec7a408387a1bf7b7d1dd222/">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=Estonian-English parallel corpus from the Estonian Classification of Economic Activities (EMTAK).   
EXTRAHTML=ELRC-2457-Estonian_Classification_Economic_Activities is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/estonian-english-parallel-corpus-from-the-estonian-classification-of-economic-activities-emtak/8f70180ab83f11e9a7e100155d0267060b99d0ceec7a408387a1bf7b7d1dd222/">https://www.elrc-share.eu</a>
# CITENOTE=
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/estonian-english-parallel-corpus-from-the-estonian-classification-of-economic-activities-emtak/8f70180ab83f11e9a7e100155d0267060b99d0ceec7a408387a1bf7b7d1dd222/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
