# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = publicDomainpublicDomain
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/government-of-ireland-programme-call-document/0ef43e348b5211ec9c1a00155d02670633674bfa6e7a4fd6aa09153da4f58fb7/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Government of Ireland Programme Call Document   
EXTRAHTML=ELRC-5124-Government_Ireland_Programme_Call_Document is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/government-of-ireland-programme-call-document/0ef43e348b5211ec9c1a00155d02670633674bfa6e7a4fd6aa09153da4f58fb7/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/government-of-ireland-programme-call-document/0ef43e348b5211ec9c1a00155d02670633674bfa6e7a4fd6aa09153da4f58fb7/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
