# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1.0

LICENSE = see WMT and IWSLT
COPYRIGHT = The data sets are distributed as part of international shared translation tasks at WMT and IWSLT. Check their websites for further information on copyrights and license agreements.

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML = The data sets are distributed as part of the <a href="https://nlp.stanford.edu/projects/nmt/">research on neural machine translation at StanfordNLP</a>.

# EXTRAHTML = Simple example corpus
# CITENOTE = 

# CONTACT = 
