# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = SETIMES2
VERSION = 


# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=<p>A parallel corpus of news articles in the Balkan languages, originally extracted from <a href="http://www.setimes.com">http://www.setimes.com</a>. The corpus is compiled by Nikola Ljubešić and is taken from <a href="http://www.nljubesic.net/resources/corpora/setimes/">http://www.nljubesic.net/resources/corpora/setimes</a> provided under the <a href="http://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA license</a></p>
EXTRAHTML=
