# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
# VERSION = v2019

RELEASE_DATE := 20191206
VERSION      := v${RELEASE_DATE}

LICENSE = CC BY 4.0
COPYRIGHT = For more information about the source, see <a href="https://www2.nict.go.jp/astrec-att/member/mutiyama/ALT/">https://www2.nict.go.jp/astrec-att/member/mutiyama/ALT/</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML = The ALT corpus is part of the <a href="http://www2.nict.go.jp/astrec-att/member/mutiyama/ALT/">Asian Language Treebank (ALT) Project</a>, consisting of twenty thousand 20,000 sentences from English Wikinews that were translated into 13 languages: Bengali, English, Filipino, Hindi, Bahasa Indonesia, Japanese, Khmer, Lao, Malay, Myanmar (Burmese), Thai, Vietnamese, Chinese (Simplified Chinese). This collection only includes the training split of the parallel data.

# EXTRAHTML = Simple example corpus
CITENOTE = Hammam Riza, Michael Purwoadi, Gunarso, Teduh Uliniansyah, Aw Ai Ti, Sharifah Mahani Aljunied, Luong Chi Mai, Vu Tat Thang, Nguyen Phuong Thai, Vichet Chea, Rapid Sun, Sethserey Sam, Sopheap Seng, Khin Mar Soe, Khin Thandar Nwet, Masao Utiyama, Chenchen Ding. (2016) "Introduction of the Asian Language Treebank" Oriental COCOSDA. (<a href="https://www2.nict.go.jp/astrec-att/member/mutiyama/ALT/ALT-Parallel-Corpus-20191206/ALT-O-COCOSDA.pdf">pdf</a>) and also acknowledge the distribution of the package via OPUS.


CONTACT = For questions, comments, etc. please email to alt-info[at]khn[dot]nict[dot]go[dot]jp.

