# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v2019

LICENSE = CC-BY 4.0
COPYRIGHT = For more information about the source, see <a href="https://www2.nict.go.jp/astrec-att/member/mutiyama/ALT/">https://www2.nict.go.jp/astrec-att/member/mutiyama/ALT/</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML = The ALT corpus is part of the <a href="http://www2.nict.go.jp/astrec-att/member/mutiyama/ALT/">Asian Language Treebank (ALT) Project</a>, consisting of twenty thousand Myanmar-English parallel sentences from news articles. The data is distributed at <a href="http://lotus.kuee.kyoto-u.ac.jp/WAT/my-en-data/"></a>

# EXTRAHTML = Simple example corpus
CITENOTE = Please, acknowledge the source <a href="http://lotus.kuee.kyoto-u.ac.jp/WAT/my-en-data/">http://lotus.kuee.kyoto-u.ac.jp/WAT/my-en-data/</a> and also acknowledge the distribution of the package via OPUS.

CONTACT = For questions, comments, etc. please email to "wat-organizer -at- googlegroups -dot- com". 

