# -*-makefile-*-
#


include ../Makefile.def
include ../../Makefile.def

# sentence-align all document pairs
# convert all bitexts to TMX
# convert all bitexts to Moses format

LANGUAGES = ar de en es fr ru zh

all: corpus

corpus: all-align

include ../../Makefile.align
include ../../Makefile.html
