# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = OpenSubtitles
VERSION = v2016

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=<p>This is a new collection of translated movie subtitles from <a href="http://www.opensubtitles.org/">http://www.opensubtitles.org/</a>. <br/><b>IMPORTANT:</b> If you use the OpenSubtitle corpus: <br/>Please, add a link to <b>http://www.opensubtitles.org/</b> to your website and to your reports and publications produced with the data! I promised this when I got the data from the providers of that website!</p> <p> This is a cleaner version of the subtitle collection using improved conversion, sentence alignment, better language checking, more meta data, ....</p><p><b>NOTE:</b> The sentence alignment files and all TMX/Moses files have been updated on 7 January, 2016. Please, download the data files once again if you use an older version!</p>

# EXTRAHTML= <p><b>WARNING!</b> This collection is not ready yet! Data sets will still change a lot. Use with care!!</p>
EXTRAHTML= <p>Look also at the <a href="${CORPUS}alt.php">intra-lingual links</a> between alternative subtitles!</p>
