# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = CC-BY-SA-4.0
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/pio-publication-window-of-cyprus-processed/064f6e8a02a111e9b7d400155d0267067dc1b859dae04b27b20a128392203bf3/">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=PIO Publication SRCHTML=This is my first parallel corpusquot;Window of CyprusSRCHTML=This is my first parallel corpusquot;  (Processed)   
EXTRAHTML=ELRC-1067-PIO_Publication_Window_Cyprus is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/pio-publication-window-of-cyprus-processed/064f6e8a02a111e9b7d400155d0267067dc1b859dae04b27b20a128392203bf3/">https://www.elrc-share.eu</a>
# CITENOTE=
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/pio-publication-window-of-cyprus-processed/064f6e8a02a111e9b7d400155d0267067dc1b859dae04b27b20a128392203bf3/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
