# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = publicDomainpublicDomain
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/bilingual-documents-bulgarian-english-in-the-field-of-transport-processed/572fcb1e6d1b11e7b7d400155d0267063b864e3c5e3b417b94b4a4799f1cb454/">ELRC share</a>Check details at <a href="https://elrc-share.eu/repository/browse/bilingual-documents-bulgarian-english-in-the-field-of-transport-processed/572fcb1e6d1b11e7b7d400155d0267063b864e3c5e3b417b94b4a4799f1cb454/">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Bilingual documents Bulgarian-English in the field of transport (Processed)   
EXTRAHTML=ELRC-408-transport is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/bilingual-documents-bulgarian-english-in-the-field-of-transport-processed/572fcb1e6d1b11e7b7d400155d0267063b864e3c5e3b417b94b4a4799f1cb454/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/bilingual-documents-bulgarian-english-in-the-field-of-transport-processed/572fcb1e6d1b11e7b7d400155d0267063b864e3c5e3b417b94b4a4799f1cb454/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
