# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = publicDomain
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/leabhran-daonad-altranais-pobail-teach-ui-riada/1ab8850ab92611e9a7e100155d0267068ea60f09ff36454abc2a2a5ca3cda9c9/">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=Leabhrán dSRCHTML=This is my first parallel corpusapos;Aonad Altranais Pobail Teach Uí Riada   
EXTRAHTML=ELRC-2466-Leabhrán_dAonad_Altranais_Pobail_Teach_Uí_Riada is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/leabhran-daonad-altranais-pobail-teach-ui-riada/1ab8850ab92611e9a7e100155d0267068ea60f09ff36454abc2a2a5ca3cda9c9/">https://www.elrc-share.eu</a>
# CITENOTE=
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/leabhran-daonad-altranais-pobail-teach-ui-riada/1ab8850ab92611e9a7e100155d0267068ea60f09ff36454abc2a2a5ca3cda9c9/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
