# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = News-Commentary
VERSION = 9.1


# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=<p>A parallel corpus of News Commentaries provided by WMT for training SMT. The source is taken from CASMACAT: <a href="http://www.casmacat.eu/corpus/news-commentary">http://www.casmacat.eu/corpus/news-commentary</a></p>
EXTRAHTML=
