# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = publicDomainpublicDomain
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/charter-of-values-of-citizenship-and-integration-processed/00c95db6c7b611e8b7d400155d026706e6dedb53f56e4c60b5b90f59c1632085/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=CHARTER OF VALUES OF CITIZENSHIP AND INTEGRATION (Processed)   
EXTRAHTML=ELRC-832-CHARTER_VALUES_CITIZENSHIP_INTEGRATION is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/charter-of-values-of-citizenship-and-integration-processed/00c95db6c7b611e8b7d400155d026706e6dedb53f56e4c60b5b90f59c1632085/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/charter-of-values-of-citizenship-and-integration-processed/00c95db6c7b611e8b7d400155d026706e6dedb53f56e4c60b5b90f59c1632085/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
