# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = CC-BY-4.0CC-BY-4.0
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/compilation-of-german-croatian-parallel-corpora-resources-used-for-training-of-nteu-machine-translation-engines/e87a8aa6b40111eb9c1a00155d026706b87f67cfb8bd4bbcb1296f2bf4a89bba/">ELRC share</a>Check details at <a href="https://elrc-share.eu/repository/browse/compilation-of-german-croatian-parallel-corpora-resources-used-for-training-of-nteu-machine-translation-engines/e87a8aa6b40111eb9c1a00155d026706b87f67cfb8bd4bbcb1296f2bf4a89bba/">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Compilation of German-Croatian parallel corpora resources used for training of NTEU Machine Translation engines.   
EXTRAHTML=ELRC-4198-NTEU_TierA is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/compilation-of-german-croatian-parallel-corpora-resources-used-for-training-of-nteu-machine-translation-engines/e87a8aa6b40111eb9c1a00155d026706b87f67cfb8bd4bbcb1296f2bf4a89bba/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/compilation-of-german-croatian-parallel-corpora-resources-used-for-training-of-nteu-machine-translation-engines/e87a8aa6b40111eb9c1a00155d026706b87f67cfb8bd4bbcb1296f2bf4a89bba/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
