

## unfortunately, this only links to some kind of yandex storage

# all: chv-ru.chv chv-ru.ru chv-en.chv chv-en.en


# chv-ru.chv:
# 	wget -O $@ https://yadi.sk/d/B4bx_c56W6zSfg

# chv-ru.ru:
# 	wget -O $@ https://yadi.sk/d/wEfXNxgEdIsbZA


# chv-en.chv:
# 	wget -O $@ https://yadi.sk/d/ZKvXjkwbI75Qmg

# chv-en.en:
# 	wget -O $@ https://yadi.sk/d/UeeL5g_M-prpTA
