# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = openUnder-PSIopenUnder-PSI
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/polish-ministry-of-foreign-affairs-youth-2011-report-processed/04e63120d10411e7b7d400155d026706c2afaea446bf42c9ab3585ef0207d9b6/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Polish Ministry of Foreign Affairs Youth 2011 Report (Processed)   
EXTRAHTML=ELRC-483-Polish_Foreign_Affairs_Youth_2011_Report is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/polish-ministry-of-foreign-affairs-youth-2011-report-processed/04e63120d10411e7b7d400155d026706c2afaea446bf42c9ab3585ef0207d9b6/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/polish-ministry-of-foreign-affairs-youth-2011-report-processed/04e63120d10411e7b7d400155d026706c2afaea446bf42c9ab3585ef0207d9b6/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
