# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = publicDomain
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/comhdhail-cumann-idirnaisiunta-na-gcoimisineiri-teanga-2019/35698eced46c11e9913100155d026706099494cb89fe4287817a3b9727e96ce8/">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=Comhdháil Cumann Idirnáisiúnta na gCoimisineirí Teanga 2019   
EXTRAHTML=ELRC-2509-Comhdháil_Cumann_Idirnáisiúnta_na_gCoimisineirí_Teanga_2019 is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/comhdhail-cumann-idirnaisiunta-na-gcoimisineiri-teanga-2019/35698eced46c11e9913100155d026706099494cb89fe4287817a3b9727e96ce8/">https://www.elrc-share.eu</a>
# CITENOTE=
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/comhdhail-cumann-idirnaisiunta-na-gcoimisineiri-teanga-2019/35698eced46c11e9913100155d026706099494cb89fe4287817a3b9727e96ce8/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
