# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = CC0-1.0CC0-1.0
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/belgian-government-bilingual-parallel-corpus-processed/7776b1f86d1b11e7b7d400155d02670695be094ae2054d26bf3064496c652636/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Belgian government bilingual parallel corpus (Processed)   
EXTRAHTML=ELRC-421-Belgian_government is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/belgian-government-bilingual-parallel-corpus-processed/7776b1f86d1b11e7b7d400155d02670695be094ae2054d26bf3064496c652636/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/belgian-government-bilingual-parallel-corpus-processed/7776b1f86d1b11e7b7d400155d02670695be094ae2054d26bf3064496c652636/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
