# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = publicDomainpublicDomain
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/financial-stability-reports-from-the-national-bank-of-poland-2015-16-processed/57d34994c23611e8b7d400155d026706871e9ae9daee4540916632e30c64ab4f/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Financial Stability Reports from the National Bank of Poland (2015-16) (Processed)   
EXTRAHTML=ELRC-799-Financial_Stability_Bank_Poland_2015_16 is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/financial-stability-reports-from-the-national-bank-of-poland-2015-16-processed/57d34994c23611e8b7d400155d026706871e9ae9daee4540916632e30c64ab4f/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/financial-stability-reports-from-the-national-bank-of-poland-2015-16-processed/57d34994c23611e8b7d400155d026706871e9ae9daee4540916632e30c64ab4f/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
