# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under /corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = Mozilla Public License 2.0
COPYRIGHT = 

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=This is a corpus of Mozilla localisation/internationalisation data compiled into TMX files and collected from this repository: <a href="https://github.com/mozilla-l10n/mt-training-data">https://github.com/mozilla-l10n/mt-training-data</a>
# EXTRAHTML=
# CITENOTE=
