# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = publicDomainpublicDomain
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/tmx-files-230919-irish-language-scheme-customer-charter-customer-action-plan/54e689c48f3011ec9c1a00155d0267063fe0c0555c1d44c199ba632343cf0005/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=TMX Files-230919-Irish Language Scheme, Customer Charter, Customer Action Plan   
EXTRAHTML=ELRC-5150-Language_Scheme_Customer_Charter_Customer_Action_Plan is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/tmx-files-230919-irish-language-scheme-customer-charter-customer-action-plan/54e689c48f3011ec9c1a00155d0267063fe0c0555c1d44c199ba632343cf0005/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/tmx-files-230919-irish-language-scheme-customer-charter-customer-action-plan/54e689c48f3011ec9c1a00155d0267063fe0c0555c1d44c199ba632343cf0005/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
