# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = openUnder-PSIopenUnder-PSI
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/bilingual-english-danish-parallel-corpus-from-national-gallery-of-denmark-website/4dea95eed13711e8b7d400155d026706d091b7ac4cb84ac88707d8f381732b43/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Bilingual English-Danish parallel corpus from National Gallery of Denmark website   
EXTRAHTML=ELRC-894-Gallery_Denmark is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/bilingual-english-danish-parallel-corpus-from-national-gallery-of-denmark-website/4dea95eed13711e8b7d400155d026706d091b7ac4cb84ac88707d8f381732b43/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/bilingual-english-danish-parallel-corpus-from-national-gallery-of-denmark-website/4dea95eed13711e8b7d400155d026706d091b7ac4cb84ac88707d8f381732b43/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
