#-*-makefile-*-
#
# Joerg Tiedemann <jorg.tiedemann@helsinki.fi>

INSTALL = install -c
INSTALL_BIN = ${INSTALL} -m 755
INSTALL_DATA = ${INSTALL} -m 644

MKDIR = mkdir -p -m 755

OPUS_HOME     = /media/OPUS
OPUS_CORPORA  = ${OPUS_HOME}/corpus
OPUS_TOOLS    = ${OPUS_HOME}/tools

ifndef JAVA_HOME
  export JAVA_HOME=/usr/lib/jvm/java
endif
