# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = sardware

## current version
VERSION = v1

LICENSE = 
COPYRIGHT = 

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Source: http://www.tradumatica.net/sardware/ - Thanks to Adrià Martin
EXTRAHTML=


DOWNLOAD_URL = http://www.tradumatica.net/sardware/resursas/memorias/