# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1.0

LICENSE = CC-BY-SA-3.0
COPYRIGHT = 

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML = The data set is part of the Kyoto Free Translation Task (KFTT). The KFTT is a task for the evaluation and development of Japanese-English machine translation systems. More information can be found on <a href="http://www.phontron.com/kftt/">http://www.phontron.com/kftt/</a>

# EXTRAHTML = Simple example corpus
CITENOTE = Please, acknowledge the source and cite the work as specified on <a href="http://www.phontron.com/kftt/">http://www.phontron.com/kftt/</a> and also acknowledge the distribution of the package via OPUS.

CONTACT = Graham Neubig, <a href="http://www.phontron.com/kftt/">http://www.phontron.com/kftt/</a> and <a href="http://www.cs.cmu.edu/~neulab/">http://www.cs.cmu.edu/~neulab/</a>
