# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*OPUS/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v2

LICENSE = CC–BY-NC-SA 4.0
COPYRIGHT = 

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=This is part if <a href="https://blogs.helsinki.fi/fiskmo-project/">fiskmö</a>, a massive parallel corpus for Finnish and Swedish.
EXTRAHTML=<p>License: <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC–BY-NC-SA 4.0</a></p>
# CITENOTE=