# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*OPUS/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = The corpus is distributed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons BY-NC-SA 4.0 license</a>
COPYRIGHT = 

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=<p>EiTB-ParCC: Parallel Corpus of Comparable News</p><p>A Basque-Spanish parallel corpus provided by Vicomtech (https://www.vicomtech.org), extracted from comparable news produced by the Basque public broadcasting group <a href="https:///www.eitb.eus">Euskal Irrati Telebista</a>.</p>
EXTRAHTML=
CITENOTE=<p>If you use any part of this corpus in your own work, please cite the following article:</p>\
<blockquote>\
@inproceedings{etchegoyhen-gete:2020:LREC2,</br/>\
  author    = {Etchegoyhen, Thierry  and  Gete, Harritxu},</br/>\
  title     = {Handle with Care: A Case Study in Comparable Corpora Exploitation for Neural Machine Translation},</br/>\
  booktitle = {Proceedings of the 12th Language Resources and Evaluation Conference},</br/>\
  month     = {May},</br/>\
  year      = {2020},</br/>\
  location   = {Marseille, France},</br/>\
  publisher = {European Language Resources Association},</br/>\
  pages     = {3792--3800}</br/>\
}</br/>\
</blockquote>
