# -*-makefile-*-
#
# to align all languag pairs on the local disc:
#
#    make HPC_CORES=16 wordalign-all-local.submit
# 

all:
	${MAKE} all-wordalign

include ../Makefile.def
include ../../Makefile.def
include ../../Makefile.wordalign
include ../../Makefile.submit
