# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under /corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = CC-BY-SA-3.0
COPYRIGHT = <a href="https://creativecommons.org/licenses/by-sa/3.0/">Wikisource</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=This is a parallel corpus compiled from <a href="https://en.wikisource.org/wiki/Salom%C3%A9">translations of Oscar Wilde’s Salome</a>, a play originally written in French. Supported by the QuantiQual Project [Irish Research Council, COALESCE/2017/117]

# EXTRAHTML=Simple example corpus
CITENOTE= Please, cite: <blockquote><pre>@article{poncelas2020esperanto,<br/>  title = {Using Multiple Subwords for Improving English-Esperanto Automated Literary Translation Quality},<br/>  author={Poncelas, Alberto and Buts, Jan and Hadley, James and Way, Andy}<br/>}</pre></blockquote>
