# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = Debian
# VERSION = 0.1
VERSION = $(shell date +%F)


# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=<p>A parallel corpus of Debian localization files. Source: <a href="http://i18n.debian.org">http://i18n.debian.org</a></p>
EXTRAHTML=
