# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = OfisPublik
VERSION = 0.1


# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Texts from the Ofis Publik ar Brezhoneg (Breton Language Board) provided by Francis Tyers
EXTRAHTML=

CITENOTE=Please <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following articles</a> if you use any part of the corpus in your own work:<br/> <ul><li>Tiedemann, J., 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012) and </li><li>Tyers, F. M. (2009) "Rule-based augmentation of training data in Breton-French statistical machine translation ". Proceedings of the 13th Annual Conference of the European Association of Machine Translation, EAMT09. pp. 213--218</ul>

