# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*OPUS/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = CC–BY 4.0
COPYRIGHT = 

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Parallel corpus of theses and dissertation abstracts in Portuguese and English from CAPES<br/>Source: <a href="https://sites.google.com/view/felipe-soares/datasets">https://sites.google.com/view/felipe-soares/datasets</a>
EXTRAHTML=A parallel corpus of theses and dissertations abstracts in English and Portuguese were collected from the CAPES website (Coordenação de Aperfeiçoamento de Pessoal de Nível Superior) - Brazil. The corpus is sentence aligned for all language pairs. Approximately 240,000 documents were collected and aligned using the Hunalign algorithm. <br/> DOI: <a href ="https://doi.org/10.6084/m9.figshare.5995519.v2">https://doi.org/10.6084/m9.figshare.5995519.v2</a></br/>If you use this corpus, please cite the following work: <blockquote>@inproceedings{soares2018parallel,<br/>  title={A Parallel Corpus of Theses and Dissertations Abstracts},<br/>  author={Soares, Felipe and Yamashita, Gabrielli Harumi and Anzanello, Michel Jose},<br/>  booktitle={International Conference on Computational Processing of the Portuguese Language},<br/>  pages={345--352},<br/>  year={2018},<br/>  organization={Springer}<br/>}</blockquote>




