# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = CC-BY-SA-3.0
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/covid-19-health-wikipedia-dataset-bilingual-en-sq/bf18c3488de811ea913100155d02670600f1e221209a455ab1f415c6de2eba5a/">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=COVID-19 - HEALTH Wikipedia dataset. Bilingual (EN-SQ)   
EXTRAHTML=ELRC-3052-wikipedia_health is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/covid-19-health-wikipedia-dataset-bilingual-en-sq/bf18c3488de811ea913100155d02670600f1e221209a455ab1f415c6de2eba5a/">https://www.elrc-share.eu</a>
# CITENOTE=
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/covid-19-health-wikipedia-dataset-bilingual-en-sq/bf18c3488de811ea913100155d02670600f1e221209a455ab1f415c6de2eba5a/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
