# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = EUbookshop
VERSION = v2


# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Corpus of documents from the EU bookshop
EXTRAHTML=Source: http://bookshop.europa.eu - Thanks to Tilde (http://www.tilde.com) for collecting the data, within the EU ICT PSP project LetsMT! (https://www.letsmt.eu/)<br/>
