


fetch:
	for i in ABOUT.md.txt devs-combo-shuf10k-raw+tok.tgz devtests-raw+tok.tgz prep.tgz train.raw.tsv.gz \
		train.v1.eng.tok.gz train.v1.lang.gz train.v1.prov.gz train.v1.src.tok.gz train.v1.tok.stats.tsv; do \
		wget https://isi.edu/~tg/data/many-eng/v1/$$i ; \
	done

