# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = publicDomainpublicDomain
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/tuarascail-bhliantuil-2018-on-roinn-dli-agus-cirt-agus-comhionannais/f566b0ec8f2e11ec9c1a00155d026706a95e4a9de02e4d048e68aaf42564feb8/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Tuarascáil Bhliantúil 2018 ón Roinn Dlí agus Cirt agus Comhionannais   
EXTRAHTML=ELRC-5149-Tuarascáil_Bhliantúil_2018_ón_Roinn_Dlí_agus_Cirt_agus_Comhionannais is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/tuarascail-bhliantuil-2018-on-roinn-dli-agus-cirt-agus-comhionannais/f566b0ec8f2e11ec9c1a00155d026706a95e4a9de02e4d048e68aaf42564feb8/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/tuarascail-bhliantuil-2018-on-roinn-dli-agus-cirt-agus-comhionannais/f566b0ec8f2e11ec9c1a00155d026706a95e4a9de02e4d048e68aaf42564feb8/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
