# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = CC-BY-SA-4.0
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/pio-publication-cyprus-has-always-been-europe-2017-en-el-processed/3037bed0029e11e9b7d400155d0267067eb7aa91b22e410295faa11327835f0c/">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=PIO Publication SRCHTML=This is my first parallel corpusquot;Cyprus has always been Europe 2017SRCHTML=This is my first parallel corpusquot; EN-EL (Processed)   
EXTRAHTML=ELRC-1065-PIO_Publication_Cyprus_has_always_been_Europe_2017 is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/pio-publication-cyprus-has-always-been-europe-2017-en-el-processed/3037bed0029e11e9b7d400155d0267067eb7aa91b22e410295faa11327835f0c/">https://www.elrc-share.eu</a>
# CITENOTE=
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/pio-publication-cyprus-has-always-been-europe-2017-en-el-processed/3037bed0029e11e9b7d400155d0267067eb7aa91b22e410295faa11327835f0c/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
