# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = MultiParaCrawl
# FILTER  = zipporah
FILTER  = bicleaner07

RELEASE = 7.1
VERSION = v${RELEASE}


PARACRAWL_RELEASE4   = https://paracrawl.eu/v4
PARACRAWL_RELEASE5   = https://paracrawl.eu/v5
PARACRAWL_RELEASE7.1 = https://paracrawl.eu

## current release to work with
PARACRAWL_RELEASE    = ${PARACRAWL_RELEASE7.1}
PARACRAWL_URL        = https://s3.amazonaws.com/web-language-models/paracrawl

## additional hidden bonus files
PARACRAWL_BONUS      = bonus/en-ha.tmx.gz bonus/en-ig.tmx.gz


# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML = Parallel corpora from Web Crawls collected in the <a href="http://paracrawl.eu/download.html">ParaCrawl project</a> and further processed for making it a multi-parallel corpus by pivoting via English. Here we only provide the additional language pairs that came out of pivoting. The bitexts for English are available from the <a href="http://opus.nlpl.eu/ParaCrawl-${VERSION}.php">ParaCrawl release</a>.
EXTRAHTML = The data is released under the <a href="https://creativecommons.org/share-your-work/public-domain/cc0/">Creative Commons CC0 license</a> ("no rights reserved"), see <a href="http://paracrawl.eu/download.html">http://paracrawl.eu/download.html</a> for more details
CITENOTE = Please, acknowledge the ParaCrawl project at <a href="http://paracrawl.eu">http://paracrawl.eu</a>. This version is derived from the original release at their website adjusted for redistribution via the OPUS corpus collection. Please, acknowledge OPUS as well for this service.
