# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under /corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = <a href="/ELRC_3254/LICENSE.pdf">CC-BY-4.0</a>
COPYRIGHT = <a href="https://www.elrc-share.eu">ELRC</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=ELRC_3254: COVID-19\ EUROPARL\ v2\ dataset.\ Multilingual\ (24\ CEF\ languages) (public data set from <a href="https://elrc-share.eu/repository/browse/covid-19-europarl-v2-dataset-multilingual-24-cef-languages/8d6f0e6692ab11ea913100155d026706c30255385cdf4a0c92e1b4fc040f0bdb/">https://www.elrc-share.eu</a>)
EXTRAHTML=For more information, please look at <a href="https://www.elrc-share.eu">https://www.elrc-share.eu</a>) and data set with ID ELRC_3254.
# CITENOTE=
