# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = openUnder-PSIopenUnder-PSI
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/electronic-exchange-of-social-security-information-documents-in-czech-english-processed/831daaca6d1b11e7b7d400155d0267064d3c98af2d9a4e1a8a73a2f961876161/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Electronic Exchange of Social Security Information documents in Czech-English (Processed)   
EXTRAHTML=ELRC-427-Electronic_Exchange_Social_Security_Information is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/electronic-exchange-of-social-security-information-documents-in-czech-english-processed/831daaca6d1b11e7b7d400155d0267064d3c98af2d9a4e1a8a73a2f961876161/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/electronic-exchange-of-social-security-information-documents-in-czech-english-processed/831daaca6d1b11e7b7d400155d0267064d3c98af2d9a4e1a8a73a2f961876161/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
