# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v3


LICENSE      = CC-BY-SA 4.0
COPYRIGHT    = The actual packaging of this parallel data is licensed under the Creative Commons CC0 license ("no rights reserved"). For take-down policy, see <a href="https://www.paracrawl.eu/releases.html">https://www.paracrawl.eu/releases.html</a>
CONTACT      = Barry Haddow (bhaddow _at_ inf _dot_ ed _dot_ ac _dot_ uk)
RELEASE_DATE = ${shell date '+%F'}


# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=This corpus contains data released for the WMT series of shared tasks. It consists of parallel wikipedia titles.

EXTRAHTML = The code used to extract the wikititles is available at <a href="https://github.com/bhaddow/wikipedia-interlanguage-titles">https://github.com/bhaddow/wikipedia-interlanguage-titles</a>
CITENOTE  = If you use the data, please cite the most recent WMT overview paper (currently https://aclanthology.info/papers/W18-6401/w18-6401) and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">acknowledge the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
