# -*-makefile-*-
#
# run sentence alignment between all file pairs for all language pairs

include ../Makefile.def

all:
	${MAKE} all-align
	${MAKE} tmx
	${MAKE} moses


include ../../Makefile.def
include ../../Makefile.align
include ../../Makefile.tmx
include ../../Makefile.moses
