# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = CC-BY-4.0CC-BY-4.0
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/letter-of-rights-for-persons-arrested-and-or-detained-processed/0102395e050811e8b7d400155d026706483f8695e5e94dc5beb5b835e17725bb/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Letter of rights for persons arrested and or detained (Processed)   
EXTRAHTML=ELRC-648-Letter_rights_persons_arrested_or_detained is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/letter-of-rights-for-persons-arrested-and-or-detained-processed/0102395e050811e8b7d400155d026706483f8695e5e94dc5beb5b835e17725bb/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/letter-of-rights-for-persons-arrested-and-or-detained-processed/0102395e050811e8b7d400155d026706483f8695e5e94dc5beb5b835e17725bb/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
