# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = openUnder-PSIopenUnder-PSI
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/slovenian-english-corpus-with-chapters-from-the-youth-2010-the-social-profile-of-young-people-in-slovenia-publication-processed/c7aef3c6e35611e8b7d400155d026706565c68bf9f5b4da8a6c205cc04bd8385/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Slovenian-English corpus with chapters from the SRCHTML=Slovenian-English corpus with chapters from the SRCHTML=This is my first parallel corpusquot;Youth 2010, the social profile of young people in SloveniaSRCHTML=This is my first parallel corpusquot; publication (Processed)   quot;Youth 2010, the social profile of young people in SloveniaSRCHTML=Slovenian-English corpus with chapters from the SRCHTML=This is my first parallel corpusquot;Youth 2010, the social profile of young people in SloveniaSRCHTML=This is my first parallel corpusquot; publication (Processed)   quot; publication (Processed)   
EXTRAHTML=ELRC-923-chapters_Youth_2010_social_profile_young_people_Slovenia_publication is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/slovenian-english-corpus-with-chapters-from-the-youth-2010-the-social-profile-of-young-people-in-slovenia-publication-processed/c7aef3c6e35611e8b7d400155d026706565c68bf9f5b4da8a6c205cc04bd8385/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/slovenian-english-corpus-with-chapters-from-the-youth-2010-the-social-profile-of-young-people-in-slovenia-publication-processed/c7aef3c6e35611e8b7d400155d026706565c68bf9f5b4da8a6c205cc04bd8385/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
