# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = WMT-News
VERSION = 1

LANGUAGES = cs de en es fr hi ru

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=<p>A parallel corpus of News Test Sets provided by WMT for training SMT: <a href="http://www.statmt.org/wmt14/">http://www.statmt.org/wmt14/</a></p>
EXTRAHTML=
