# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = Tanzil
# VERSION = 0.1
VERSION = $(shell date +%F)


# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=This is a collection of Quran translations compiled by the <a href="http://tanzil.net/">Tanzil project</a><h3>Terms of Use</h3><p>The translations provided at this page are for non-commercial purposes only. If used otherwise, you need to obtain necessary permission from the translator or the publisher.</p><p>If you are using more than three of the following translations in a website or application, we require you to put a link back to <a href="http://tanzil.net/trans">this page</a> to make sure that subsequent users have access to the latest updates.</p>
EXTRAHTML=
