# -*-makefile-*-
#


SHELL              := bash

# name & version of the corpus

CORPUS             := CCMatrix
VERSION            := v1
SOURCE_URL         := https://github.com/facebookresearch/LASER/tree/master/tasks/CCMatrix
UNSORTED_SENTALIGN := 1
SKIP_TMX_UNIQ      := 1

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML = <p>This corpus has been extracted from web crawls using the margin-based bitext mining techniques described at <a href="https://github.com/facebookresearch/LASER/tree/master/tasks/CCMatrix">https://github.com/facebookresearch/LASER/tree/master/tasks/CCMatrix</a>.</p>



CITENOTE = Please, cite the following papers: \
<ul><li>Holger Schwenk, Guillaume Wenzek, Sergey Edunov, Edouard Grave, Armand Joulin and Angela Fan, <a href="https://arxiv.org/abs/1911.04944">CCMatrix: Mining Billions of High-Quality Parallel Sentences on the WEB</a></li>\
<li>Angela Fan, Shruti Bhosale, Holger Schwenk, Zhiyi Ma, Ahmed El-Kishky, Siddharth Goyal, Mandeep Baines, Onur Celebi, Guillaume Wenzek, Vishrav Chaudhary, Naman Goyal, Tom Birch, Vitaliy Liptchinsky, Sergey Edunov, Edouard Grave, Michael Auli, and Armand Joulin. <a href="https://arxiv.org/abs/2010.11125">Beyond English-Centric Multilingual Machine Translation</a></li></ul> \
and also acknowledge OPUS for the service provided here by citing <a href="https://www.aclweb.org/anthology/L12-1246/">Jörg Tiedemann, <it>Parallel Data, Tools and Interfaces in OPUS</it></a> (<a href="https://www.aclweb.org/anthology/L12-1246.bib">bib</a>, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf">pdf</a>)
