# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = 
COPYRIGHT = 

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML = This is a mulitlingual corpus compiled by Nart Tlisha, distributed at <a href="https://github.com/danielinux7/Multilingual-Parallel-Corpus">https://github.com/danielinux7/Multilingual-Parallel-Corpus</a>. Please, refer to terms and conditions specified in that repository.

CONTACT = Nart Tlisha, e-mail: daniel.abzakh@gmail.com

# EXTRAHTML = Simple example corpus
# CITENOTE=
