# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = openUnder-PSI
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/bulgarian-english-corpus-of-legislation-from-the-republic-of-bulgaria-ministry-of-energy-website-processed/8a5356bcee7711e8b7d400155d0267068e24cb784154488d86adffe317b6ae54/">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=Bulgarian-English corpus of legislation from the Republic of Bulgaria Ministry of Energy website (Processed)   
EXTRAHTML=ELRC-1000-legislation_Bulgaria_Energy is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/bulgarian-english-corpus-of-legislation-from-the-republic-of-bulgaria-ministry-of-energy-website-processed/8a5356bcee7711e8b7d400155d0267068e24cb784154488d86adffe317b6ae54/">https://www.elrc-share.eu</a>
# CITENOTE=
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/bulgarian-english-corpus-of-legislation-from-the-republic-of-bulgaria-ministry-of-energy-website-processed/8a5356bcee7711e8b7d400155d0267068e24cb784154488d86adffe317b6ae54/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
