# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = UN
VERSION = 20090831


# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=This is a collection of translated documents from the United Nations originally compiled into a translation memory by Alexandre Rafalovitch, Robert Dale (see <a href="http://uncorpora.org">http://uncorpora.org</a>). Please cite <a href="http://uncorpora.org/Rafalovitch_Dale_MT_Summit_2009.pdf">Alexandre Rafalovitch, Robert Dale. 2009. United Nations General Assembly Resolutions: A Six-Language Parallel Corpus. In Proceedings of the MT Summit XII, pages 292-299, Ottawa, Canada, August</a>
EXTRAHTML=
