# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = NLOD-1.0NLOD-1.0
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/bilingual-nb-en-parallel-corpus-from-the-norways-petroleum-website/16006a8ce6f511e7b7d400155d0267061a1e5775094d4d0bb5c9e044adbb8386/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Bilingual nb-en parallel corpus from the Norway’s petroleum website   
EXTRAHTML=ELRC-561-Norway_petroleum is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/bilingual-nb-en-parallel-corpus-from-the-norways-petroleum-website/16006a8ce6f511e7b7d400155d0267061a1e5775094d4d0bb5c9e044adbb8386/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/bilingual-nb-en-parallel-corpus-from-the-norways-petroleum-website/16006a8ce6f511e7b7d400155d0267061a1e5775094d4d0bb5c9e044adbb8386/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
