# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = ParaCrawl-Bonus

RELEASE = 9
VERSION = v${RELEASE}

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML = Parallel corpora from Web Crawls collected in the <a href="http://paracrawl.eu/download.html">ParaCrawl project (bonus releases)</a>
EXTRAHTML = The data is released under the <a href="https://creativecommons.org/share-your-work/public-domain/cc0/">Creative Commons CC0 license</a> ("no rights reserved"), see <a href="http://paracrawl.eu/download.html">http://paracrawl.eu/download.html</a> for more details
CITENOTE = Please, acknowledge the ParaCrawl project at <a href="http://paracrawl.eu">http://paracrawl.eu</a>. This version is derived from the original release at their website adjusted for redistribution via the OPUS corpus collection. More information about the releases on South and East Asian Languages can be found in <a href="https://aclanthology.org/2024.wmt-1.132/">Philipp Koehn: Neural Methods for Aligning Large-Scale Parallel Corpora from the Web for South and East Asian Languages</a>. Please, acknowledge OPUS as well for this service.
