# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = publicDomain
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/estatuto-da-vitima-em-pt-e-eng/ca8aa184da2311e9913100155d0267067d6465a887014d75b5e09abc0bff49bc/">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=Estatuto da Vítima em PT e ENG   
EXTRAHTML=ELRC-2536-Estatuto_da_Vítima_em_PT_e_ENG is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/estatuto-da-vitima-em-pt-e-eng/ca8aa184da2311e9913100155d0267067d6465a887014d75b5e09abc0bff49bc/">https://www.elrc-share.eu</a>
# CITENOTE=
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/estatuto-da-vitima-em-pt-e-eng/ca8aa184da2311e9913100155d0267067d6465a887014d75b5e09abc0bff49bc/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
