# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = CC-BY-4.0CC-BY-4.0
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/government-offices-in-iceland-legislation-and-regulations/6ad42ad5c56411eb9c1a00155d026706aac46ebe9197417e999d6f2b768c0bf7/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Government Offices in Iceland – Legislation and regulations   
EXTRAHTML=ELRC-4327-Government_Offices_Iceland_Legislation_regulations is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/government-offices-in-iceland-legislation-and-regulations/6ad42ad5c56411eb9c1a00155d026706aac46ebe9197417e999d6f2b768c0bf7/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/government-offices-in-iceland-legislation-and-regulations/6ad42ad5c56411eb9c1a00155d026706aac46ebe9197417e999d6f2b768c0bf7/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
