# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = NLOD-1.0NLOD-1.0
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/bilingual-english-norwegian-parallel-corpus-from-norges-bank-investment-management-website/532c2ec2e57a11e7b7d400155d026706ea9134d7106b464ca2225c7240c49ebe/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Bilingual English-Norwegian parallel corpus from Norges Bank Investment Management website   
EXTRAHTML=ELRC-535-www.nbim.no is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/bilingual-english-norwegian-parallel-corpus-from-norges-bank-investment-management-website/532c2ec2e57a11e7b7d400155d026706ea9134d7106b464ca2225c7240c49ebe/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/bilingual-english-norwegian-parallel-corpus-from-norges-bank-investment-management-website/532c2ec2e57a11e7b7d400155d026706ea9134d7106b464ca2225c7240c49ebe/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
