# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = openUnder-PSI
COPYRIGHT = Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=Preasráiteas ó Choláiste na Tríonóide, Baile Átha Cliath   
EXTRAHTML=ELRC-5142-Preasráiteas_ó_Choláiste_na_Tríonóide_Baile_Átha_Cliath_5142 is a public data set distributed by the <a href="https://www.elrc-share.eu">https://www.elrc-share.eu</a>
# CITENOTE=
