# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*OPUS/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = CC0
COPYRIGHT = <a href="https://en.corpus.chv.su/content/about.html">chuvash.org</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML= The <a href="https://en.corpus.chv.su/">Chuvash bilingual corpus</a> is part of the "Chuvash language laboratory". The laboratory is a project created and developed by an initiative of activists and supported by their own funds. Its goal is to provide digital resources for the Chuvash language.
# EXTRAHTML=Simple example corpus
# CITENOTE=
