# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = CC0-1.0
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/english-to-norwegian-bokmal-translation-memories-from-amesto-translations/d0e67d363f6011e9a4d400155d0267063d302c65dfe34fcea860ae7b6c5d3071/">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=English to Norwegian Bokmål translation memories from Amesto Translations   
EXTRAHTML=ELRC-1805-Norwegian_Bokmål_Amesto_ennb is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/english-to-norwegian-bokmal-translation-memories-from-amesto-translations/d0e67d363f6011e9a4d400155d0267063d302c65dfe34fcea860ae7b6c5d3071/">https://www.elrc-share.eu</a>
# CITENOTE=
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/english-to-norwegian-bokmal-translation-memories-from-amesto-translations/d0e67d363f6011e9a4d400155d0267063d302c65dfe34fcea860ae7b6c5d3071/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
