# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = publicDomain
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/estatuto-dos-deputados/cfabc682c9a911e9913100155d026706ae9cd4ff21674591a986b44f8b414ad4/">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=Estatuto dos Deputados   
EXTRAHTML=ELRC-2480-Estatuto_dos_Deputados is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/estatuto-dos-deputados/cfabc682c9a911e9913100155d026706ae9cd4ff21674591a986b44f8b414ad4/">https://www.elrc-share.eu</a>
# CITENOTE=
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/estatuto-dos-deputados/cfabc682c9a911e9913100155d026706ae9cd4ff21674591a986b44f8b414ad4/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
