# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = publicDomainpublicDomain
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/audioguide-for-the-military-history-museum-in-vienna-processed/75771bfe6d1b11e7b7d400155d0267067c1f85f9336a4d48891fba475c4dce2b/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Audioguide for the Military History Museum in Vienna (Processed)   
EXTRAHTML=ELRC-420-Audioguide_Military_History_Museum_Vienna is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/audioguide-for-the-military-history-museum-in-vienna-processed/75771bfe6d1b11e7b7d400155d0267067c1f85f9336a4d48891fba475c4dce2b/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/audioguide-for-the-military-history-museum-in-vienna-processed/75771bfe6d1b11e7b7d400155d0267067c1f85f9336a4d48891fba475c4dce2b/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
