# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*OPUS/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = <a href="/ELRA-W0247/LICENSE.pdf">openUnder-PSI</a>
COPYRIGHT = <a href="https://www.elrc-share.eu">ELRC</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=ELRA-W0247: ELRC_858_Parallel\ corpus\ (en-pl)\ from\ the\ Export (public data set from <a href="https://www.elrc-share.eu">https://www.elrc-share.eu</a>)
EXTRAHTML=For more information, please look at <a href="https://www.elrc-share.eu">https://www.elrc-share.eu</a>) and data set with ID ELRA-W0247. Data Quality Indicators can be seen in this <a href="/ELRA-W0247/VALREP.pdf">document</a>.
# CITENOTE=
