# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = XLEnt
VERSION = v1

SOURCE_URL = http://data.statmt.org/xlent/

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML = <p>This corpus was created by mining CCAligned, CCMatrix, and WikiMatrix parallel sentences. These three sources were themselves extracted from web data from Commoncrawl Snapshots and Wikipedia snapshots. Entity pairs were obtained by performing named entity recognition and typing on English sentences and projecting labels to non-English aligned sentence pairs. No claims of intellectual property are made on the work of preparation of the corpus.</p> \
<p>XLEnt consists of parallel entity mentions in 120 languages aligned with English. These entity pairs were constructed by performing named entity recognition (NER) and typing on English sentences from mined sentence pairs. These extracted English entity labels and types were projected to the non-English sentences through word alignment. Word alignment was performed by combining three alignment signals ((1) word co-occurence alignment with FastAlign (2) semantic alignment using LASER embeddings, and (3) phonetic alignment via transliteration) into a unified word-alignment model. This lexical/semantic/phonetic alignment approach yielded more than 160 million aligned entity pairs in 120 languages paired with English. Recognizing that each English is often aligned to mulitple entities in different target languages, we can join on English entities to obtain aligned entity pairs that directly pair two non-English entities (e.g., Arabic-French) </p> \
<p>The original distribution is available from <a href="http://data.statmt.org/xlent/">http://data.statmt.org/xlent/</a></p>


CITENOTE = If you use the dataset or code, please cite (<a href="http://data.statmt.org/xlent/elkishky_XLEnt.pdf">pdf</a>): \
<blockquote><pre>\
@inproceedings{elkishky_xlent_2021,</br>\
 author = {El-Kishky, Ahmed and Renduchintala, Adi and Cross, James and Guzmán, Francisco and Koehn, Philipp},</br>\
 booktitle = {Preprint},</br>\
 title = {{XLEnt}: Mining Cross-lingual Entities with Lexical-Semantic-Phonetic Word Alignment}</br>,\
 year = {2021},</br>\
 address = "Online",</br>\
}</pre></blockquote> \
and, please, acknowledge <a href="https://www.aclweb.org/anthology/L12-1246/">OPUS</a> (<a href="https://www.aclweb.org/anthology/L12-1246.bib">bib</a>, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf">pdf</a>) as well for this service.

