# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = CC-BY-4.0
COPYRIGHT = 

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML = This repository contains parallel language corpus links for popular Indian languages developed as part of the <a href="http://anuvaad.org/">Anuvaad project</a>. The Anuvaad Parallel Corpus is available from <a href="https://github.com/project-anuvaad/anuvaad-parallel-corpus">https://github.com/project-anuvaad/anuvaad-parallel-corpus</a>.

EXTRAHTML = Please reach out to nlp-nmt@tarento.com for any clarification/interpretation/usage of the linked datasets.
CONTACT = nlp-nmt@tarento.com
# CITENOTE=
