# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = publicDomain
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/tuarascalaca-bliantula-na-roinne-leanai-agus-gnothai-oige/6fca9c429cd211e9a7e100155d026706247b4ffe9f154d13a156fa7bf8bf06ba/">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=Tuarascálaca Bliantúla na Roinne Leanaí agus Gnóthaí Óige   
EXTRAHTML=ELRC-2414-Tuarascálaca_Bliantúla_na_Roinne_Leanaí_agus_Gnóthaí_Óige is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/tuarascalaca-bliantula-na-roinne-leanai-agus-gnothai-oige/6fca9c429cd211e9a7e100155d026706247b4ffe9f154d13a156fa7bf8bf06ba/">https://www.elrc-share.eu</a>
# CITENOTE=
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/tuarascalaca-bliantula-na-roinne-leanai-agus-gnothai-oige/6fca9c429cd211e9a7e100155d026706247b4ffe9f154d13a156fa7bf8bf06ba/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
