# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = publicDomain
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/raitis-airgeadais-ollscoil-mha-nuad-2017-2018/017aa060a6f611e9a7e100155d026706c5fe0841b98d4b19825b8a7557d5b0a2/">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=Ráitis Airgeadais Ollscoil Mhá Nuad  2017 - 2018   
EXTRAHTML=ELRC-2439-Ráitis_Airgeadais_Ollscoil_Mhá_Nuad_2017_2018 is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/raitis-airgeadais-ollscoil-mha-nuad-2017-2018/017aa060a6f611e9a7e100155d026706c5fe0841b98d4b19825b8a7557d5b0a2/">https://www.elrc-share.eu</a>
# CITENOTE=
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/raitis-airgeadais-ollscoil-mha-nuad-2017-2018/017aa060a6f611e9a7e100155d026706c5fe0841b98d4b19825b8a7557d5b0a2/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
