# -*-makefile-*-
#

all:
	${MAKE} ACTION=wordalign-align all-wordalign

include ../Makefile.def
include ../../Makefile.def

CORPUSXML        = ${CORPUSHOME}/parsed
CORPUSWORDALIGN  = ${CORPUSHOME}/wordalign-ud
CORPUSDIC        = ${CORPUSHOME}/dic-ud

include ../../Makefile.wordalign




