# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = CC-BY-4.0
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/ministry-of-development-funds-and-regional-policy-dataset-processed/ca14a632565a11eb9d5900155d026706f5349f3021c641e4959fc0b29c606dae/">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=Ministry of Development Funds and Regional Policy Dataset (Processed)   
EXTRAHTML=ELRC-3852-Development_Funds_Regional_Policy is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/ministry-of-development-funds-and-regional-policy-dataset-processed/ca14a632565a11eb9d5900155d026706f5349f3021c641e4959fc0b29c606dae/">https://www.elrc-share.eu</a>
# CITENOTE=
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/ministry-of-development-funds-and-regional-policy-dataset-processed/ca14a632565a11eb9d5900155d026706f5349f3021c641e4959fc0b29c606dae/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
