# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*OPUS/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = <a href="/ELRC_401/LICENSE.pdf">Public\ Domain</a>
COPYRIGHT = <a href="https://www.elrc-share.eu">ELRC</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=ELRC_401: Parallel\ texts\ from\ Swedish\ Labour\ market\ agency.\ Part\ 2\ (Processed) (public data set from <a href="https://elrc-share.eu/repository/browse/parallel-texts-from-swedish-labour-market-agency-part-2-processed/4701dc966d1b11e7b7d400155d0267060552ac67c5894efeade9ecef2910ec0c/">https://www.elrc-share.eu</a>)
EXTRAHTML=For more information, please look at <a href="https://www.elrc-share.eu">https://www.elrc-share.eu</a>) and data set with ID ELRC_401.
# CITENOTE=
