# -*-makefile-*-
#
# name & version of the corpus



## - specify the server of the OPUS repository
## - specify the repository name and the user name
## (this assumes that ssh keys are set up to access the server)

# OPUSRR_HOST = vm0081.kaj.pouta.csc.fi
OPUSRR_HOST   = vm1637.kaj.pouta.csc.fi
OPUSRR_USER   = cloud-user
REPO_NAME     = infopankki
REPO_USER     = joerg



## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
## TODO: can we take that from the OPUSRR repo?
VERSION = v1

LICENSE = 
COPYRIGHT = 

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML   = This is my first parallel corpus
EXTRAHTML = Simple example corpus
# CITENOTE =
