# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = KDE4
VERSION = 


# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=<p>A parallel corpus of KDE4 localization files (v.2).</p>
EXTRAHTML=
