# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under /corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = <a href="/ELRC_3382/LICENSE.pdf">CC-BY-4.0</a>
COPYRIGHT = <a href="https://www.elrc-share.eu">ELRC</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=ELRC_3382: COVID-19\ EU\ presscorner\ v1\ dataset.\ Multilingual\ (CEF\ languages) (public data set from <a href="https://elrc-share.eu/repository/browse/covid-19-eu-presscorner-v1-dataset-multilingual-cef-languages/0f41b80e968911ea913100155d0267061a602e936edc49138512eef56af9ec09/">https://www.elrc-share.eu</a>)
EXTRAHTML=For more information, please look at <a href="https://www.elrc-share.eu">https://www.elrc-share.eu</a>) and data set with ID ELRC_3382.
# CITENOTE=
