# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under /corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = CC0 1.0
COPYRIGHT = 

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=<p>This is a multilingual parallel corpus created from translations of the Bible <a href="https://github.com/christos-c/bible-corpus">compiled by Christos Christodoulopoulos and Mark Steedman</a>.</p>
EXTRAHTML=<p>License: CC0 1.0</p>
CITENOTE=Please cite OPUS and <a href="http://link.springer.com/article/10.1007/s10579-014-9287-y">A massively parallel corpus: the Bible in 100 languages</a>, Christos Christodoulopoulos and Mark Steedman, *Language Resources and Evaluation*, 49 (2)
