# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*OPUS/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = <a href="https://creativecommons.org/share-your-work/public-domain/cc0/">Creative Commons CC0 license</a>
COPYRIGHT = All content is made publicly available through a Creative Commons CC0 license.

LANGUAGES = en uk

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=This is a corpus compiled by Faheem Kirefu as part of the <a href="http://summa-project.eu/">SUMMA project</a>
# EXTRAHTML=Simple example corpus
# CITENOTE=
