# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = DOGC
VERSION = v3
LICENSE = CC-0
COPYRIGHT = see <a href="http://www.gencat.cat/web/cat/avis_legal.htm">Legal notice</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=This is a collection of documents from the official journal of the Catalan Goverment in Catalan and Spanish provided by Antoni Oliver Gonzalez from the Universitat Oberta de Catalunya. The data is provided under the license provided at <a href="http://www.gencat.cat/web/cat/avis_legal.htm">http://www.gencat.cat/web/cat/avis_legal.htm</a>

EXTRAHTML=
