# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1


LICENSE      = CC-BY-SA 4.0
COPYRIGHT    = The corpus is released under the CC-BY-4.0, in other words the corpus can be freely shared and adapted as long as appropriate
credit is give. https://creativecommons.org/licenses/by/4.0/
CONTACT      = Barry Haddow (bhaddow _at_ inf _dot_ ed _dot_ ac _dot_ uk)
RELEASE_DATE = 2020-01-27


# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML = This directory contains the releases of the pmindia corpus. It is a parallel corpus containing 13 Indian languages,\
plus English, derived from the Prime Minister of India's news updates (https://www.pmindia.gov.in/en/news-updates/).\
We release a sentence aligned version of the corpus, as well as the monolingual text extracted from the articles.

EXTRAHTML = The code for crawling and aligning is available at <a href="https://github.com/bhaddow/pmindia-crawler">https://github.com/bhaddow/pmindia-crawler</a>

CITENOTE  = <h3>Acknowledgements</h3>\
This work has received funding from the European Unions Horizon 2020 research and innovation programme \
under grant agreement No 825299 (Gourmet). We thank the Prime Minister's Office of the Government of India for making the content \
available for re-distribution. If you use the corpus, please cite: \
<blockquote><pre><br/>\
@ARTICLE{2020arXiv200109907H,<br/>\
       author = {{Haddow}, Barry and {Kirefu}, Faheem},<br/>\
        title = "{PMIndia -- A Collection of Parallel Corpora of Languages of India}",<br/>\
      journal = {arXiv e-prints},<br/>\
     keywords = {Computer Science - Computation and Language},<br/>\
         year = "2020",<br/>\
        month = "Jan",<br/>\
          eid = {arXiv:2001.09907},<br/>\
        pages = {arXiv:2001.09907},<br/>\
archivePrefix = {arXiv},<br/>\
       eprint = {2001.09907}<br/>\
}<br/>\
</blockquote></pre>\
and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">acknowledge the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
