# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under /corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = CC-BY-SA-4.0
COPYRIGHT = 

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=A parallel news corpus in Turkish, Kurdish and English; Source: <a href="https://d-ataman.github.io/bianet/">https://d-ataman.github.io/bianet/</a><br/>Bianet collects 3,214 Turkish articles with their sentence-aligned Kurdish or English translations from the <a href="http://bianet.org/">Bianet online newspaper</a>. This corpus is distributed under the CC-BY-SA-4.0 open license.
EXTRAHTML=
CITENOTE=If you use Bianet, please cite: Ataman, D. (2018) Bianet: A Parallel News Corpus in Turkish, Kurdish and English. In Proceedings of the LREC 2018 Workshop MLP-Moment. pp. 14-17. <a href="http://lrec-conf.org/workshops/lrec2018/W19/pdf/6_W19.pdf">pdf</a>