# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = publicDomainpublicDomain
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/financial-stability-reports-from-the-national-bank-of-poland-2013-14-processed/7002c136c22a11e8b7d400155d026706ecb794909c3f4f46acbe659d85f8f703/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Financial Stability Reports from the National Bank of Poland (2013-14) (Processed)   
EXTRAHTML=ELRC-798-Financial_Stability_Bank_Poland_2013_14 is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/financial-stability-reports-from-the-national-bank-of-poland-2013-14-processed/7002c136c22a11e8b7d400155d026706ecb794909c3f4f46acbe659d85f8f703/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/financial-stability-reports-from-the-national-bank-of-poland-2013-14-processed/7002c136c22a11e8b7d400155d026706ecb794909c3f4f46acbe659d85f8f703/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
