# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under /corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = <a href="/ELRC_406/LICENSE.pdf">Public\ Domain</a>
COPYRIGHT = <a href="https://www.elrc-share.eu">ELRC</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=ELRC_406: Parallel\ texts\ from\ Swedish\ Labour\ market\ agency\ (Processed) (public data set from <a href="https://elrc-share.eu/repository/browse/parallel-texts-from-swedish-labour-market-agency-processed/53212c0c6d1b11e7b7d400155d0267069785bf0178354f1484b6950e4a5a92c2/">https://www.elrc-share.eu</a>)
EXTRAHTML=For more information, please look at <a href="https://www.elrc-share.eu">https://www.elrc-share.eu</a>) and data set with ID ELRC_406.
# CITENOTE=
