# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under /corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = 
COPYRIGHT = Please respect the <a href="https://www.ted.com/about/our-organization/our-policies-terms">TED Talks Usage Policy</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML = This dataset is compiled from TED talk subtitles and distributed through <a href="http://phontron.com/data/ted_talks.tar.gz">phontron.com</a>. The package here includes the training data only (development and test data are not included in this package). The transcripts have been <a href="https://www.ted.com/participate/translate">translated by a global community of volunteers</a> to more than 100 languages. The parallel corpus and the code fopr cerating it is available from <a href="https://github.com/UKPLab/sentence-transformers/blob/master/docs/datasets/TED2020.md">https://www.ted.com/participate/translate</a>
EXTRAHTML = Note that this corpus is tokenized in its original form. For this package we applied automatic de-tokenization using the moses tools. This is not perfect and may miss some de-tokenization steps.
# CITENOTE=

