# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = CC-BY-4.0CC-BY-4.0
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/polish-food-4-food-policy-dataset-processed/688e1f9ad0ef11e7b7d400155d02670621eb1efcdbce4b99aaf454e2849b8b1b/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Polish Food 4 SRCHTML=Polish Food 4 SRCHTML=This is my first parallel corpus Food Policy Dataset (Processed)    Food Policy Dataset (Processed)   
EXTRAHTML=ELRC-478-Polish_Food_4_Food_Policy is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/polish-food-4-food-policy-dataset-processed/688e1f9ad0ef11e7b7d400155d02670621eb1efcdbce4b99aaf454e2849b8b1b/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/polish-food-4-food-policy-dataset-processed/688e1f9ad0ef11e7b7d400155d02670621eb1efcdbce4b99aaf454e2849b8b1b/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
