# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = openUnder-PSIopenUnder-PSI
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/polish-english-parallel-corpus-from-the-website-geoportalgovpl-processed/28470674e81b11e8b7d400155d026706a1d18e79272f4df5a71835ec03f66c42/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Polish-English parallel corpus from the website SRCHTML=Polish-English parallel corpus from the website SRCHTML=This is my first parallel corpusquot;geoportal.gov.plSRCHTML=This is my first parallel corpusquot; (Processed)   quot;geoportal.gov.plSRCHTML=Polish-English parallel corpus from the website SRCHTML=This is my first parallel corpusquot;geoportal.gov.plSRCHTML=This is my first parallel corpusquot; (Processed)   quot; (Processed)   
EXTRAHTML=ELRC-970-geoportal.gov.pl is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/polish-english-parallel-corpus-from-the-website-geoportalgovpl-processed/28470674e81b11e8b7d400155d026706a1d18e79272f4df5a71835ec03f66c42/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/polish-english-parallel-corpus-from-the-website-geoportalgovpl-processed/28470674e81b11e8b7d400155d026706a1d18e79272f4df5a71835ec03f66c42/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
