# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = CC-BY-4.0
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/covid-19-antibiotic-dataset-bilingual-en-lt/abace546904511ea913100155d0267068f6e75f9e87f426d8eb879f79a828a08/">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=COVID-19 ANTIBIOTIC dataset. Bilingual (EN-LT)   
EXTRAHTML=ELRC-3205-antibiotic is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/covid-19-antibiotic-dataset-bilingual-en-lt/abace546904511ea913100155d0267068f6e75f9e87f426d8eb879f79a828a08/">https://www.elrc-share.eu</a>
# CITENOTE=
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/covid-19-antibiotic-dataset-bilingual-en-lt/abace546904511ea913100155d0267068f6e75f9e87f426d8eb879f79a828a08/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
