# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*OPUS/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = 
COPYRIGHT = 

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=This is an aligned Ada 83 Reference Manual from English to Russian provided by Maxim Reznik. The English version is available <a href="https://www.adaic.org/ada-resources/standards/ada83/">online</a> and the Russian translation was made in 1988 by the Ada working group in USSR. Since then it was published as USSR standard (ГОСТ 27831-88). It is available on the web as PDF.
EXTRAHTML=
