# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = publicDomainpublicDomain
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/a-crisis-in-the-number-of-competent-irish-language-speakers-in-the-state-system-shown-clearly-in-the-coimisineir-teangas-report/11f1fd588f3311ec9c1a00155d02670651e2a92cbe8a4e77b29fa9f9cf3fa829/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=A crisis in the number of competent Irish language speakers in the State system shown clearly in the Coimisinéir Teanga’s report   
EXTRAHTML=ELRC-5153-A_crisis_number_competent_Irish_language_speakers_State_system_shown_clearly_Coimisinéir_Teanga_report is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/a-crisis-in-the-number-of-competent-irish-language-speakers-in-the-state-system-shown-clearly-in-the-coimisineir-teangas-report/11f1fd588f3311ec9c1a00155d02670651e2a92cbe8a4e77b29fa9f9cf3fa829/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/a-crisis-in-the-number-of-competent-irish-language-speakers-in-the-state-system-shown-clearly-in-the-coimisineir-teangas-report/11f1fd588f3311ec9c1a00155d02670651e2a92cbe8a4e77b29fa9f9cf3fa829/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
