# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = JRC-Acquis
VERSION = 3.0

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=<p>JRC-Acquis is a collection of legislative text of the European Union and currently comprises selected texts written between the 1950s and now. <br/>Source: <a href="https://ec.europa.eu/jrc/en/language-technologies/jrc-acquis">https://ec.europa.eu/jrc/en/language-technologies/jrc-acquis</a><br/>The version at OPUS is based on the paragraph-aligned corpus provided by JRC (aligned using hunalign) but adds also sentence boundary markup and sentence alignment for all sentence pairs. The format is also converted to be compatible with OPUS but contains the same information otherwise (content and metadata). For licensing issues please check <a href="https://ec.europa.eu/jrc/en/language-technologies/jrc-acquis#Usage%20conditions%20/%20Licensing%20issues">the official website of JRC-Acquis</a></p>
EXTRAHTML=
