# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = publicDomain
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/lei-organica-2-de-2008/ad7dfa3ac9a911e9913100155d0267066105e1b64c6743a9abf4e89f87da42fd/">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=Lei orgânica 2 de 2008   
EXTRAHTML=ELRC-2479-Lei_orgânica_2_2008 is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/lei-organica-2-de-2008/ad7dfa3ac9a911e9913100155d0267066105e1b64c6743a9abf4e89f87da42fd/">https://www.elrc-share.eu</a>
# CITENOTE=
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/lei-organica-2-de-2008/ad7dfa3ac9a911e9913100155d0267066105e1b64c6743a9abf4e89f87da42fd/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
