# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = CC-BY-4.0
COPYRIGHT = Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=Tuairisc a thug Máire Nic Shiubhlaigh, Aisteoir Tionscanta de chuid Amharlann na Mainistreach, ar ghéilleadh gharastún mhonarcha Jacob   
EXTRAHTML=ELRC-2452-Tuairisc_a_thug_Máire_Nic_Shiubhlaigh_Aisteoir_Tionscanta_chuid_Amharlann_na_Mainistreach_ar_ghéilleadh_gharastún_mhonarcha_Jacob is a public data set distributed by the <a href="https://www.elrc-share.eu">https://www.elrc-share.eu</a>
# CITENOTE=
