# -*-makefile-*-
#

LANGUAGES=ar be bg bs ca cn cs cy da de el en es et fi fr fr_BE ga gd hr hu is it ja lb lt lv mk mt nb nl nl_BE pl po pt ro ru sh sk sl sq sr sv sw tc tr uk zh

all:
	${MAKE} all-wordalign

include ../Makefile.def
include ../../Makefile.def
include ../../Makefile.wordalign

