# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  := ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}


## current version

TRANSLATION_DUMPS_URL := https://translatewiki.net/static/translation-dump
# VERSION  := $(patsubst translations-%.tar.gz,v%,$(shell wget -q -O - ${TRANSLATION_DUMPS_URL}/info.txt))
VERSION    := v2025-01-01
SOURCE_URL := <a href="https://translatewiki.net/static/translation-dump">https://translatewiki.net/static/translation-dump</a>


CONTACT := The core team behind translatewiki.net can be found at <a href="https://translatewiki.net/wiki/Project:About">https://translatewiki.net/wiki/Project:About</a> and you can leave a message at their <a href="https://translatewiki.net/wiki/Support">support pages</a>


LICENSE := <a target="_blank" href="https://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>
COPYRIGHT := Use the translations in translatewiki.net at your own risk. They are intended to be useful but translatewiki.net cannot guarantee the validity of the content found here. translatewiki.net and its editors do not provide any warranty on the contents whatsoever, whether expressed, implied, or statutory, including, but not limited to, any warranty of merchantability or fitness for a particular purpose or any warranty that the contents will be error-free. More information about copyrights and disclaimers can be found at <a href="https://translatewiki.net/wiki/Project:About">https://translatewiki.net/wiki/Project:About</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML := All translations included in this corpus are published by <a href="translatewiki.net">translatewiki.net</a>. The data is taken from their translation dumps at <a href="https://translatewiki.net/static/translation-dump">https://translatewiki.net/static/translation-dump</a>. translatewiki.net is a translation community and a localisation platform for free and open source projects. It started out with localisation for MediaWiki. Later support was added for MediaWiki extensions, FreeCol, and other free and open source projects. See the complete list of supported projects. translatewiki.net is an independent open source project. The translation functionality is provided by the MediaWiki extension Translate. This wiki always contains experimental code, and may be broken occasionally. Please be patient, problems are usually dealt with quickly.


# EXTRAHTML = Simple example corpus
# CITENOTE=

