# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*OPUS/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = <a href="/ELRC_417/LICENSE.pdf">Public\ Domain</a>
COPYRIGHT = <a href="https://www.elrc-share.eu">ELRC</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=ELRC_417: Parallel\ texts\ from\ Swedish\ Work\ environment\ Authority\ (Processed) (public data set from <a href="https://elrc-share.eu/repository/browse/parallel-texts-from-swedish-work-environment-authority-processed/6d39b3986d1b11e7b7d400155d0267069bec5b7998364ea5b17c8b96e42b39e3/">https://www.elrc-share.eu</a>)
EXTRAHTML=For more information, please look at <a href="https://www.elrc-share.eu">https://www.elrc-share.eu</a>) and data set with ID ELRC_417.
# CITENOTE=
