# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = CC-BY-SA-4.0
COPYRIGHT = Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header
# CITENOTE if you want to change the default reference to be cited

SRCHTML=Preasráitis Gaois, Fiontar SRCHTML=This is my first parallel corpus Scoil na Gaeilge, DCU (1)   
EXTRAHTML=ELRC-2424-Preasráitis_Gaois_Fiontar_Scoil_na_Gaeilge_DCU_Part1 is a public data set distributed by the <a href="https://www.elrc-share.eu">https://www.elrc-share.eu</a>
# CITENOTE=
