# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = publicDomainpublicDomain
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/convention-against-torture-and-other-cruel-inhuman-or-degrading-treatment-or-punishment-united-nations-french-english-greek-processed/c86365a08c1111e8b7d400155d026706b5569edaae9b4c5ca25cdb2e4a037de5/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Convention against Torture and Other Cruel, Inhuman or Degrading Treatment or Punishment - United Nations (French-English-Greek) (Processed)   
EXTRAHTML=ELRC-745-Convention_against_Torture_Other_Cruel_Inhuman_or_Degrading_Treatment_or_Punishment_United_Nations is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/convention-against-torture-and-other-cruel-inhuman-or-degrading-treatment-or-punishment-united-nations-french-english-greek-processed/c86365a08c1111e8b7d400155d026706b5569edaae9b4c5ca25cdb2e4a037de5/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/convention-against-torture-and-other-cruel-inhuman-or-degrading-treatment-or-punishment-united-nations-french-english-greek-processed/c86365a08c1111e8b7d400155d026706b5569edaae9b4c5ca25cdb2e4a037de5/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
