# -*-makefile-*-
#
# name & version of the corpus


## CORPUSNAME = subdir under OPUS/corpus/
CORPUS  = ${firstword ${subst /, ,$(shell pwd | sed 's|^.*/corpus/\(.*\)$$|\1|')}}

## current version
VERSION = v1

LICENSE = CC-BY-4.0CC-BY-4.0
COPYRIGHT = Check details at <a href="https://elrc-share.eu/repository/browse/bilingual-english-norwegian-parallel-corpus-from-the-norways-governments-website/a79eb8f6e56311e7b7d400155d0267067f9ec5ca3b1944e7a3d1c7ba509744ba/">ELRC share</a>Check details at <a href="https://www.elrc-share.eu">ELRC share</a>

# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML=Bilingual English-Norwegian parallel corpus from The NorwaySRCHTML=Bilingual English-Norwegian parallel corpus from The NorwaySRCHTML=This is my first parallel corpusapos;s Governments website   apos;s Governments website   
EXTRAHTML=ELRC-518-www.regjeringen.no is a public data set distributed by the <a href="https://elrc-share.eu/repository/browse/bilingual-english-norwegian-parallel-corpus-from-the-norways-governments-website/a79eb8f6e56311e7b7d400155d0267067f9ec5ca3b1944e7a3d1c7ba509744ba/">https://www.elrc-share.eu</a>
CITENOTE = Please acknowledge the <a href="https://elrc-share.eu/repository/browse/bilingual-english-norwegian-parallel-corpus-from-the-norways-governments-website/a79eb8f6e56311e7b7d400155d0267067f9ec5ca3b1944e7a3d1c7ba509744ba/">original sources and providers</a> of the data and also <a href="http://opus.lingfil.uu.se/LREC2012.txt">cite the following article</a> if you use the OPUS packages and downloads in your own work:<br/> J. Tiedemann, 2012, <a href="http://www.lrec-conf.org/proceedings/lrec2012/pdf/463_Paper.pdf"><i>Parallel Data, Tools and Interfaces in OPUS.</i></a> In Proceedings of the 8th International Conference on Language Resources and Evaluation (LREC 2012)
